#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#

unexport MAKEFILE_LIST
MK_NOGENDEPS := $(filter clean,$(MAKECMDGOALS))
override PKGDIR = nortos
XDCINCS = -I. -I$(strip $(subst ;, -I,$(subst $(space),\$(space),$(XPKGPATH))))
XDCCFGDIR = package/cfg/

#
# The following dependencies ensure package.mak is rebuilt
# in the event that some included BOM script changes.
#
ifneq (clean,$(MAKECMDGOALS))
/opt/ti/xdctools_3_61_00_16_core/packages/xdc/utils.js:
package.mak: /opt/ti/xdctools_3_61_00_16_core/packages/xdc/utils.js
/opt/ti/xdctools_3_61_00_16_core/packages/xdc/xdc.tci:
package.mak: /opt/ti/xdctools_3_61_00_16_core/packages/xdc/xdc.tci
/opt/ti/xdctools_3_61_00_16_core/packages/xdc/template.xs:
package.mak: /opt/ti/xdctools_3_61_00_16_core/packages/xdc/template.xs
/opt/ti/xdctools_3_61_00_16_core/packages/xdc/om2.xs:
package.mak: /opt/ti/xdctools_3_61_00_16_core/packages/xdc/om2.xs
/opt/ti/xdctools_3_61_00_16_core/packages/xdc/xmlgen.xs:
package.mak: /opt/ti/xdctools_3_61_00_16_core/packages/xdc/xmlgen.xs
/opt/ti/xdctools_3_61_00_16_core/packages/xdc/xmlgen2.xs:
package.mak: /opt/ti/xdctools_3_61_00_16_core/packages/xdc/xmlgen2.xs
/opt/ti/xdctools_3_61_00_16_core/packages/xdc/Warnings.xs:
package.mak: /opt/ti/xdctools_3_61_00_16_core/packages/xdc/Warnings.xs
/opt/ti/xdctools_3_61_00_16_core/packages/xdc/IPackage.xs:
package.mak: /opt/ti/xdctools_3_61_00_16_core/packages/xdc/IPackage.xs
/opt/ti/xdctools_3_61_00_16_core/packages/xdc/package.xs:
package.mak: /opt/ti/xdctools_3_61_00_16_core/packages/xdc/package.xs
/opt/ti/xdctools_3_61_00_16_core/packages/xdc/services/global/Clock.xs:
package.mak: /opt/ti/xdctools_3_61_00_16_core/packages/xdc/services/global/Clock.xs
/opt/ti/xdctools_3_61_00_16_core/packages/xdc/services/global/Trace.xs:
package.mak: /opt/ti/xdctools_3_61_00_16_core/packages/xdc/services/global/Trace.xs
/opt/ti/xdctools_3_61_00_16_core/packages/xdc/bld/bld.js:
package.mak: /opt/ti/xdctools_3_61_00_16_core/packages/xdc/bld/bld.js
/opt/ti/xdctools_3_61_00_16_core/packages/xdc/bld/BuildEnvironment.xs:
package.mak: /opt/ti/xdctools_3_61_00_16_core/packages/xdc/bld/BuildEnvironment.xs
/opt/ti/xdctools_3_61_00_16_core/packages/xdc/bld/PackageContents.xs:
package.mak: /opt/ti/xdctools_3_61_00_16_core/packages/xdc/bld/PackageContents.xs
/opt/ti/xdctools_3_61_00_16_core/packages/xdc/bld/_gen.xs:
package.mak: /opt/ti/xdctools_3_61_00_16_core/packages/xdc/bld/_gen.xs
/opt/ti/xdctools_3_61_00_16_core/packages/xdc/bld/Library.xs:
package.mak: /opt/ti/xdctools_3_61_00_16_core/packages/xdc/bld/Library.xs
/opt/ti/xdctools_3_61_00_16_core/packages/xdc/bld/Executable.xs:
package.mak: /opt/ti/xdctools_3_61_00_16_core/packages/xdc/bld/Executable.xs
/opt/ti/xdctools_3_61_00_16_core/packages/xdc/bld/Repository.xs:
package.mak: /opt/ti/xdctools_3_61_00_16_core/packages/xdc/bld/Repository.xs
/opt/ti/xdctools_3_61_00_16_core/packages/xdc/bld/Configuration.xs:
package.mak: /opt/ti/xdctools_3_61_00_16_core/packages/xdc/bld/Configuration.xs
/opt/ti/xdctools_3_61_00_16_core/packages/xdc/bld/Script.xs:
package.mak: /opt/ti/xdctools_3_61_00_16_core/packages/xdc/bld/Script.xs
/opt/ti/xdctools_3_61_00_16_core/packages/xdc/bld/Manifest.xs:
package.mak: /opt/ti/xdctools_3_61_00_16_core/packages/xdc/bld/Manifest.xs
/opt/ti/xdctools_3_61_00_16_core/packages/xdc/bld/Utils.xs:
package.mak: /opt/ti/xdctools_3_61_00_16_core/packages/xdc/bld/Utils.xs
/opt/ti/xdctools_3_61_00_16_core/packages/xdc/bld/ITarget.xs:
package.mak: /opt/ti/xdctools_3_61_00_16_core/packages/xdc/bld/ITarget.xs
/opt/ti/xdctools_3_61_00_16_core/packages/xdc/bld/ITarget2.xs:
package.mak: /opt/ti/xdctools_3_61_00_16_core/packages/xdc/bld/ITarget2.xs
/opt/ti/xdctools_3_61_00_16_core/packages/xdc/bld/ITarget3.xs:
package.mak: /opt/ti/xdctools_3_61_00_16_core/packages/xdc/bld/ITarget3.xs
/opt/ti/xdctools_3_61_00_16_core/packages/xdc/bld/ITargetFilter.xs:
package.mak: /opt/ti/xdctools_3_61_00_16_core/packages/xdc/bld/ITargetFilter.xs
/opt/ti/xdctools_3_61_00_16_core/packages/xdc/bld/package.xs:
package.mak: /opt/ti/xdctools_3_61_00_16_core/packages/xdc/bld/package.xs
/app/unity_application/sdk/simplelink_cc32xx_sdk_4_10_00_07/kernel/tirtos/packages/coresdk.bld:
package.mak: /app/unity_application/sdk/simplelink_cc32xx_sdk_4_10_00_07/kernel/tirtos/packages/coresdk.bld
/app/unity_application/sdk/simplelink_cc32xx_sdk_4_10_00_07/kernel/tirtos/packages/ti/targets/ITarget.xs:
package.mak: /app/unity_application/sdk/simplelink_cc32xx_sdk_4_10_00_07/kernel/tirtos/packages/ti/targets/ITarget.xs
/app/unity_application/sdk/simplelink_cc32xx_sdk_4_10_00_07/kernel/tirtos/packages/ti/targets/C28_large.xs:
package.mak: /app/unity_application/sdk/simplelink_cc32xx_sdk_4_10_00_07/kernel/tirtos/packages/ti/targets/C28_large.xs
/app/unity_application/sdk/simplelink_cc32xx_sdk_4_10_00_07/kernel/tirtos/packages/ti/targets/C28_float.xs:
package.mak: /app/unity_application/sdk/simplelink_cc32xx_sdk_4_10_00_07/kernel/tirtos/packages/ti/targets/C28_float.xs
/app/unity_application/sdk/simplelink_cc32xx_sdk_4_10_00_07/kernel/tirtos/packages/ti/targets/package.xs:
package.mak: /app/unity_application/sdk/simplelink_cc32xx_sdk_4_10_00_07/kernel/tirtos/packages/ti/targets/package.xs
/app/unity_application/sdk/simplelink_cc32xx_sdk_4_10_00_07/kernel/tirtos/packages/ti/targets/arm/elf/IArm.xs:
package.mak: /app/unity_application/sdk/simplelink_cc32xx_sdk_4_10_00_07/kernel/tirtos/packages/ti/targets/arm/elf/IArm.xs
/app/unity_application/sdk/simplelink_cc32xx_sdk_4_10_00_07/kernel/tirtos/packages/ti/targets/arm/elf/package.xs:
package.mak: /app/unity_application/sdk/simplelink_cc32xx_sdk_4_10_00_07/kernel/tirtos/packages/ti/targets/arm/elf/package.xs
/app/unity_application/sdk/simplelink_cc32xx_sdk_4_10_00_07/kernel/tirtos/packages/gnu/targets/arm/ITarget.xs:
package.mak: /app/unity_application/sdk/simplelink_cc32xx_sdk_4_10_00_07/kernel/tirtos/packages/gnu/targets/arm/ITarget.xs
/app/unity_application/sdk/simplelink_cc32xx_sdk_4_10_00_07/kernel/tirtos/packages/gnu/targets/arm/_utils.xs:
package.mak: /app/unity_application/sdk/simplelink_cc32xx_sdk_4_10_00_07/kernel/tirtos/packages/gnu/targets/arm/_utils.xs
/app/unity_application/sdk/simplelink_cc32xx_sdk_4_10_00_07/kernel/tirtos/packages/gnu/targets/arm/GCArmv6.xs:
package.mak: /app/unity_application/sdk/simplelink_cc32xx_sdk_4_10_00_07/kernel/tirtos/packages/gnu/targets/arm/GCArmv6.xs
/app/unity_application/sdk/simplelink_cc32xx_sdk_4_10_00_07/kernel/tirtos/packages/gnu/targets/arm/GCArmv7A.xs:
package.mak: /app/unity_application/sdk/simplelink_cc32xx_sdk_4_10_00_07/kernel/tirtos/packages/gnu/targets/arm/GCArmv7A.xs
/app/unity_application/sdk/simplelink_cc32xx_sdk_4_10_00_07/kernel/tirtos/packages/gnu/targets/arm/IM.xs:
package.mak: /app/unity_application/sdk/simplelink_cc32xx_sdk_4_10_00_07/kernel/tirtos/packages/gnu/targets/arm/IM.xs
/app/unity_application/sdk/simplelink_cc32xx_sdk_4_10_00_07/kernel/tirtos/packages/gnu/targets/arm/M3.xs:
package.mak: /app/unity_application/sdk/simplelink_cc32xx_sdk_4_10_00_07/kernel/tirtos/packages/gnu/targets/arm/M3.xs
/app/unity_application/sdk/simplelink_cc32xx_sdk_4_10_00_07/kernel/tirtos/packages/gnu/targets/arm/A8F.xs:
package.mak: /app/unity_application/sdk/simplelink_cc32xx_sdk_4_10_00_07/kernel/tirtos/packages/gnu/targets/arm/A8F.xs
/app/unity_application/sdk/simplelink_cc32xx_sdk_4_10_00_07/kernel/tirtos/packages/gnu/targets/arm/A9F.xs:
package.mak: /app/unity_application/sdk/simplelink_cc32xx_sdk_4_10_00_07/kernel/tirtos/packages/gnu/targets/arm/A9F.xs
/app/unity_application/sdk/simplelink_cc32xx_sdk_4_10_00_07/kernel/tirtos/packages/gnu/targets/arm/A15F.xs:
package.mak: /app/unity_application/sdk/simplelink_cc32xx_sdk_4_10_00_07/kernel/tirtos/packages/gnu/targets/arm/A15F.xs
/app/unity_application/sdk/simplelink_cc32xx_sdk_4_10_00_07/kernel/tirtos/packages/gnu/targets/arm/A53F.xs:
package.mak: /app/unity_application/sdk/simplelink_cc32xx_sdk_4_10_00_07/kernel/tirtos/packages/gnu/targets/arm/A53F.xs
/app/unity_application/sdk/simplelink_cc32xx_sdk_4_10_00_07/kernel/tirtos/packages/gnu/targets/arm/package.xs:
package.mak: /app/unity_application/sdk/simplelink_cc32xx_sdk_4_10_00_07/kernel/tirtos/packages/gnu/targets/arm/package.xs
package.mak: package.bld
/app/unity_application/sdk/simplelink_cc32xx_sdk_4_10_00_07/source/ti/drivers/xdcArgParser.xs:
package.mak: /app/unity_application/sdk/simplelink_cc32xx_sdk_4_10_00_07/source/ti/drivers/xdcArgParser.xs
/app/unity_application/sdk/simplelink_cc32xx_sdk_4_10_00_07/source/ti/drivers/libBuilder.xs:
package.mak: /app/unity_application/sdk/simplelink_cc32xx_sdk_4_10_00_07/source/ti/drivers/libBuilder.xs
endif

ti.targets.arm.elf.M4.rootDir ?= /opt/ti/ccs/tools/compiler/ti-cgt-arm_20.2.1.LTS
ti.targets.arm.elf.packageBase ?= /app/unity_application/sdk/simplelink_cc32xx_sdk_4_10_00_07/kernel/tirtos/packages/ti/targets/arm/elf/
gnu.targets.arm.M4.rootDir ?= /usr
gnu.targets.arm.packageBase ?= /app/unity_application/sdk/simplelink_cc32xx_sdk_4_10_00_07/kernel/tirtos/packages/gnu/targets/arm/
.PRECIOUS: $(XDCCFGDIR)/%.oem4
.PHONY: all,em4 .dlls,em4 .executables,em4 test,em4
all,em4: .executables,em4
.executables,em4: .libraries,em4
.executables,em4: .dlls,em4
.dlls,em4: .libraries,em4
.libraries,em4: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,em4
	@$(ECHO) xdc .executables,em4
	@$(ECHO) xdc .libraries,em4
	@$(ECHO) xdc .dlls,em4

.PRECIOUS: $(XDCCFGDIR)/%.om4g
.PHONY: all,m4g .dlls,m4g .executables,m4g test,m4g
all,m4g: .executables,m4g
.executables,m4g: .libraries,m4g
.executables,m4g: .dlls,m4g
.dlls,m4g: .libraries,m4g
.libraries,m4g: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,m4g
	@$(ECHO) xdc .executables,m4g
	@$(ECHO) xdc .libraries,m4g
	@$(ECHO) xdc .dlls,m4g


all: .executables 
.executables: .libraries .dlls
.libraries: .interfaces

PKGCFGS := $(wildcard package.xs) package/build.cfg
.interfaces: package/package.xdc.inc package/package.defs.h package.xdc $(PKGCFGS)

-include package/package.xdc.dep
package/%.xdc.inc package/%_nortos.c package/%.defs.h: %.xdc $(PKGCFGS)
	@$(MSG) generating interfaces for package nortos" (because $@ is older than $(firstword $?))" ...
	$(XSRUN) -f xdc/services/intern/cmd/build.xs $(MK_IDLOPTS) -m package/package.xdc.dep -i package/package.xdc.inc package.xdc

ifeq (,$(MK_NOGENDEPS))
-include package/package.cfg.dep
endif

package/package.cfg.xdc.inc: .interfaces $(XDCROOT)/packages/xdc/cfg/cfginc.js package.xdc
	@$(MSG) generating schema include file list ...
	$(CONFIG) -f $(XDCROOT)/packages/xdc/cfg/cfginc.js nortos $@

.libraries,em4 .libraries: lib/nortos_cc32xx.aem4

-include lib/nortos_cc32xx.aem4.mak
lib/nortos_cc32xx.aem4: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/nortos_cc32xx/package/package_nortos.oem4 package/lib/lib/nortos_cc32xx/dpl/posix_sleep.oem4 package/lib/lib/nortos_cc32xx/dpl/DebugP_nortos.oem4 package/lib/lib/nortos_cc32xx/dpl/MutexP_nortos.oem4 package/lib/lib/nortos_cc32xx/./NoRTOS.oem4 package/lib/lib/nortos_cc32xx/dpl/QueueP_nortos.oem4 package/lib/lib/nortos_cc32xx/dpl/SemaphoreP_nortos.oem4 package/lib/lib/nortos_cc32xx/dpl/SwiP_nortos.oem4 package/lib/lib/nortos_cc32xx/dpl/SystemP_nortos.oem4 package/lib/lib/nortos_cc32xx/dpl/ClockPSysTick_nortos.oem4 package/lib/lib/nortos_cc32xx/dpl/HwiPCC32XX_nortos.oem4 package/lib/lib/nortos_cc32xx/dpl/PowerCC32XX_nortos.oem4 package/lib/lib/nortos_cc32xx/startup/startup_cc32xx_ccs.oem4  into $@ ...
	$(ti.targets.arm.elf.M4.rootDir)/bin/armar  rq $@   package/lib/lib/nortos_cc32xx/package/package_nortos.oem4 package/lib/lib/nortos_cc32xx/dpl/posix_sleep.oem4 package/lib/lib/nortos_cc32xx/dpl/DebugP_nortos.oem4 package/lib/lib/nortos_cc32xx/dpl/MutexP_nortos.oem4 package/lib/lib/nortos_cc32xx/./NoRTOS.oem4 package/lib/lib/nortos_cc32xx/dpl/QueueP_nortos.oem4 package/lib/lib/nortos_cc32xx/dpl/SemaphoreP_nortos.oem4 package/lib/lib/nortos_cc32xx/dpl/SwiP_nortos.oem4 package/lib/lib/nortos_cc32xx/dpl/SystemP_nortos.oem4 package/lib/lib/nortos_cc32xx/dpl/ClockPSysTick_nortos.oem4 package/lib/lib/nortos_cc32xx/dpl/HwiPCC32XX_nortos.oem4 package/lib/lib/nortos_cc32xx/dpl/PowerCC32XX_nortos.oem4 package/lib/lib/nortos_cc32xx/startup/startup_cc32xx_ccs.oem4 
lib/nortos_cc32xx.aem4: export C_DIR=
lib/nortos_cc32xx.aem4: PATH:=$(ti.targets.arm.elf.M4.rootDir)/bin/:$(PATH)

clean,em4 clean::
	-$(RM) lib/nortos_cc32xx.aem4
.libraries,m4g .libraries: lib/nortos_cc32xx.am4g

-include lib/nortos_cc32xx.am4g.mak
lib/nortos_cc32xx.am4g: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/nortos_cc32xx/package/package_nortos.om4g package/lib/lib/nortos_cc32xx/dpl/posix_sleep.om4g package/lib/lib/nortos_cc32xx/dpl/DebugP_nortos.om4g package/lib/lib/nortos_cc32xx/dpl/MutexP_nortos.om4g package/lib/lib/nortos_cc32xx/./NoRTOS.om4g package/lib/lib/nortos_cc32xx/dpl/QueueP_nortos.om4g package/lib/lib/nortos_cc32xx/dpl/SemaphoreP_nortos.om4g package/lib/lib/nortos_cc32xx/dpl/SwiP_nortos.om4g package/lib/lib/nortos_cc32xx/dpl/SystemP_nortos.om4g package/lib/lib/nortos_cc32xx/dpl/ClockPSysTick_nortos.om4g package/lib/lib/nortos_cc32xx/dpl/HwiPCC32XX_nortos.om4g package/lib/lib/nortos_cc32xx/dpl/PowerCC32XX_nortos.om4g package/lib/lib/nortos_cc32xx/startup/startup_cc32xx_gcc.om4g  into $@ ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-ar  cr $@   package/lib/lib/nortos_cc32xx/package/package_nortos.om4g package/lib/lib/nortos_cc32xx/dpl/posix_sleep.om4g package/lib/lib/nortos_cc32xx/dpl/DebugP_nortos.om4g package/lib/lib/nortos_cc32xx/dpl/MutexP_nortos.om4g package/lib/lib/nortos_cc32xx/./NoRTOS.om4g package/lib/lib/nortos_cc32xx/dpl/QueueP_nortos.om4g package/lib/lib/nortos_cc32xx/dpl/SemaphoreP_nortos.om4g package/lib/lib/nortos_cc32xx/dpl/SwiP_nortos.om4g package/lib/lib/nortos_cc32xx/dpl/SystemP_nortos.om4g package/lib/lib/nortos_cc32xx/dpl/ClockPSysTick_nortos.om4g package/lib/lib/nortos_cc32xx/dpl/HwiPCC32XX_nortos.om4g package/lib/lib/nortos_cc32xx/dpl/PowerCC32XX_nortos.om4g package/lib/lib/nortos_cc32xx/startup/startup_cc32xx_gcc.om4g 
lib/nortos_cc32xx.am4g: export LD_LIBRARY_PATH=

clean,m4g clean::
	-$(RM) lib/nortos_cc32xx.am4g
test:;
%,copy:
	@$(if $<,,$(MSG) don\'t know how to build $*; exit 1)
	@$(MSG) cp $< $@
	$(RM) $@
	$(CP) $< $@
package_nortos.oem4,copy : package/lib/lib/nortos_cc32xx/package/package_nortos.oem4
package_nortos.sem4,copy : package/lib/lib/nortos_cc32xx/package/package_nortos.sem4
posix_sleep.oem4,copy : package/lib/lib/nortos_cc32xx/dpl/posix_sleep.oem4
posix_sleep.sem4,copy : package/lib/lib/nortos_cc32xx/dpl/posix_sleep.sem4
DebugP_nortos.oem4,copy : package/lib/lib/nortos_cc32xx/dpl/DebugP_nortos.oem4
DebugP_nortos.sem4,copy : package/lib/lib/nortos_cc32xx/dpl/DebugP_nortos.sem4
MutexP_nortos.oem4,copy : package/lib/lib/nortos_cc32xx/dpl/MutexP_nortos.oem4
MutexP_nortos.sem4,copy : package/lib/lib/nortos_cc32xx/dpl/MutexP_nortos.sem4
NoRTOS.oem4,copy : package/lib/lib/nortos_cc32xx/./NoRTOS.oem4
NoRTOS.sem4,copy : package/lib/lib/nortos_cc32xx/./NoRTOS.sem4
QueueP_nortos.oem4,copy : package/lib/lib/nortos_cc32xx/dpl/QueueP_nortos.oem4
QueueP_nortos.sem4,copy : package/lib/lib/nortos_cc32xx/dpl/QueueP_nortos.sem4
SemaphoreP_nortos.oem4,copy : package/lib/lib/nortos_cc32xx/dpl/SemaphoreP_nortos.oem4
SemaphoreP_nortos.sem4,copy : package/lib/lib/nortos_cc32xx/dpl/SemaphoreP_nortos.sem4
SwiP_nortos.oem4,copy : package/lib/lib/nortos_cc32xx/dpl/SwiP_nortos.oem4
SwiP_nortos.sem4,copy : package/lib/lib/nortos_cc32xx/dpl/SwiP_nortos.sem4
SystemP_nortos.oem4,copy : package/lib/lib/nortos_cc32xx/dpl/SystemP_nortos.oem4
SystemP_nortos.sem4,copy : package/lib/lib/nortos_cc32xx/dpl/SystemP_nortos.sem4
ClockPSysTick_nortos.oem4,copy : package/lib/lib/nortos_cc32xx/dpl/ClockPSysTick_nortos.oem4
ClockPSysTick_nortos.sem4,copy : package/lib/lib/nortos_cc32xx/dpl/ClockPSysTick_nortos.sem4
HwiPCC32XX_nortos.oem4,copy : package/lib/lib/nortos_cc32xx/dpl/HwiPCC32XX_nortos.oem4
HwiPCC32XX_nortos.sem4,copy : package/lib/lib/nortos_cc32xx/dpl/HwiPCC32XX_nortos.sem4
PowerCC32XX_nortos.oem4,copy : package/lib/lib/nortos_cc32xx/dpl/PowerCC32XX_nortos.oem4
PowerCC32XX_nortos.sem4,copy : package/lib/lib/nortos_cc32xx/dpl/PowerCC32XX_nortos.sem4
startup_cc32xx_ccs.oem4,copy : package/lib/lib/nortos_cc32xx/startup/startup_cc32xx_ccs.oem4
startup_cc32xx_ccs.sem4,copy : package/lib/lib/nortos_cc32xx/startup/startup_cc32xx_ccs.sem4
package_nortos.om4g,copy : package/lib/lib/nortos_cc32xx/package/package_nortos.om4g
package_nortos.sm4g,copy : package/lib/lib/nortos_cc32xx/package/package_nortos.sm4g
posix_sleep.om4g,copy : package/lib/lib/nortos_cc32xx/dpl/posix_sleep.om4g
posix_sleep.sm4g,copy : package/lib/lib/nortos_cc32xx/dpl/posix_sleep.sm4g
DebugP_nortos.om4g,copy : package/lib/lib/nortos_cc32xx/dpl/DebugP_nortos.om4g
DebugP_nortos.sm4g,copy : package/lib/lib/nortos_cc32xx/dpl/DebugP_nortos.sm4g
MutexP_nortos.om4g,copy : package/lib/lib/nortos_cc32xx/dpl/MutexP_nortos.om4g
MutexP_nortos.sm4g,copy : package/lib/lib/nortos_cc32xx/dpl/MutexP_nortos.sm4g
NoRTOS.om4g,copy : package/lib/lib/nortos_cc32xx/./NoRTOS.om4g
NoRTOS.sm4g,copy : package/lib/lib/nortos_cc32xx/./NoRTOS.sm4g
QueueP_nortos.om4g,copy : package/lib/lib/nortos_cc32xx/dpl/QueueP_nortos.om4g
QueueP_nortos.sm4g,copy : package/lib/lib/nortos_cc32xx/dpl/QueueP_nortos.sm4g
SemaphoreP_nortos.om4g,copy : package/lib/lib/nortos_cc32xx/dpl/SemaphoreP_nortos.om4g
SemaphoreP_nortos.sm4g,copy : package/lib/lib/nortos_cc32xx/dpl/SemaphoreP_nortos.sm4g
SwiP_nortos.om4g,copy : package/lib/lib/nortos_cc32xx/dpl/SwiP_nortos.om4g
SwiP_nortos.sm4g,copy : package/lib/lib/nortos_cc32xx/dpl/SwiP_nortos.sm4g
SystemP_nortos.om4g,copy : package/lib/lib/nortos_cc32xx/dpl/SystemP_nortos.om4g
SystemP_nortos.sm4g,copy : package/lib/lib/nortos_cc32xx/dpl/SystemP_nortos.sm4g
ClockPSysTick_nortos.om4g,copy : package/lib/lib/nortos_cc32xx/dpl/ClockPSysTick_nortos.om4g
ClockPSysTick_nortos.sm4g,copy : package/lib/lib/nortos_cc32xx/dpl/ClockPSysTick_nortos.sm4g
HwiPCC32XX_nortos.om4g,copy : package/lib/lib/nortos_cc32xx/dpl/HwiPCC32XX_nortos.om4g
HwiPCC32XX_nortos.sm4g,copy : package/lib/lib/nortos_cc32xx/dpl/HwiPCC32XX_nortos.sm4g
PowerCC32XX_nortos.om4g,copy : package/lib/lib/nortos_cc32xx/dpl/PowerCC32XX_nortos.om4g
PowerCC32XX_nortos.sm4g,copy : package/lib/lib/nortos_cc32xx/dpl/PowerCC32XX_nortos.sm4g
startup_cc32xx_gcc.om4g,copy : package/lib/lib/nortos_cc32xx/startup/startup_cc32xx_gcc.om4g
startup_cc32xx_gcc.sm4g,copy : package/lib/lib/nortos_cc32xx/startup/startup_cc32xx_gcc.sm4g

$(XDCCFGDIR)%.c $(XDCCFGDIR)%.h $(XDCCFGDIR)%.xdl: $(XDCCFGDIR)%.cfg $(XDCROOT)/packages/xdc/cfg/Main.xs | .interfaces
	@$(MSG) "configuring $(_PROG_NAME) from $< ..."
	$(CONFIG) $(_PROG_XSOPTS) xdc.cfg $(_PROG_NAME) $(XDCCFGDIR)$*.cfg $(XDCCFGDIR)$*

.PHONY: release,nortos
ifeq (,$(MK_NOGENDEPS))
-include package/rel/nortos.tar.dep
endif
package/rel/nortos/nortos/package/package.rel.xml: package/package.bld.xml
package/rel/nortos/nortos/package/package.rel.xml: package/build.cfg
package/rel/nortos/nortos/package/package.rel.xml: package/package.xdc.inc
package/rel/nortos/nortos/package/package.rel.xml: package.bld
package/rel/nortos/nortos/package/package.rel.xml: ./dpl
package/rel/nortos/nortos/package/package.rel.xml: ./startup
package/rel/nortos/nortos/package/package.rel.xml: ./posix
package/rel/nortos/nortos/package/package.rel.xml: ./NoRTOS.h
package/rel/nortos/nortos/package/package.rel.xml: package/package.cfg.xdc.inc
package/rel/nortos/nortos/package/package.rel.xml: lib/nortos_cc32xx.aem4
package/rel/nortos/nortos/package/package.rel.xml: package/package_nortos.c
package/rel/nortos/nortos/package/package.rel.xml: dpl/posix_sleep.c
package/rel/nortos/nortos/package/package.rel.xml: dpl/DebugP_nortos.c
package/rel/nortos/nortos/package/package.rel.xml: dpl/MutexP_nortos.c
package/rel/nortos/nortos/package/package.rel.xml: ./NoRTOS.c
package/rel/nortos/nortos/package/package.rel.xml: dpl/QueueP_nortos.c
package/rel/nortos/nortos/package/package.rel.xml: dpl/SemaphoreP_nortos.c
package/rel/nortos/nortos/package/package.rel.xml: dpl/SwiP_nortos.c
package/rel/nortos/nortos/package/package.rel.xml: dpl/SystemP_nortos.c
package/rel/nortos/nortos/package/package.rel.xml: dpl/ClockPSysTick_nortos.c
package/rel/nortos/nortos/package/package.rel.xml: dpl/HwiPCC32XX_nortos.c
package/rel/nortos/nortos/package/package.rel.xml: dpl/PowerCC32XX_nortos.c
package/rel/nortos/nortos/package/package.rel.xml: startup/startup_cc32xx_ccs.c
package/rel/nortos/nortos/package/package.rel.xml: lib/nortos_cc32xx.am4g
package/rel/nortos/nortos/package/package.rel.xml: startup/startup_cc32xx_gcc.c
package/rel/nortos/nortos/package/package.rel.xml: .force
	@$(MSG) generating external release references $@ ...
	$(XS) $(JSENV) -f $(XDCROOT)/packages/xdc/bld/rel.js $(MK_RELOPTS) . $@

../../exports/nortos.tar: package/rel/nortos.xdc.inc package/rel/nortos/nortos/package/package.rel.xml
	@$(MSG) making release file $@ "(because of $(firstword $?))" ...
	-$(RM) $@
	$(call MKRELTAR,package/rel/nortos.xdc.inc,package/rel/nortos.tar.dep)


release release,nortos: all ../../exports/nortos.tar
clean:: .clean
	-$(RM) package/rel/nortos.xdc.inc
	-$(RM) package/rel/nortos.tar.dep

clean:: .clean
	-$(RM) .libraries $(wildcard .libraries,*)
clean:: 
	-$(RM) .dlls $(wildcard .dlls,*)
#
# The following clean rule removes user specified
# generated files or directories.
#
	-$(RMDIR) lib/

ifneq (clean,$(MAKECMDGOALS))
ifeq (,$(wildcard lib))
    $(shell $(MKDIR) lib)
endif
ifeq (,$(wildcard package))
    $(shell $(MKDIR) package)
endif
ifeq (,$(wildcard package/cfg))
    $(shell $(MKDIR) package/cfg)
endif
ifeq (,$(wildcard package/lib))
    $(shell $(MKDIR) package/lib)
endif
ifeq (,$(wildcard package/rel))
    $(shell $(MKDIR) package/rel)
endif
ifeq (,$(wildcard package/internal))
    $(shell $(MKDIR) package/internal)
endif
ifeq (,$(wildcard ../../exports))
    $(shell $(MKDIR) ../../exports)
endif
ifeq (,$(wildcard package/lib/lib))
    $(shell $(MKDIR) package/lib/lib)
endif
ifeq (,$(wildcard package/lib/lib/nortos_cc32xx))
    $(shell $(MKDIR) package/lib/lib/nortos_cc32xx)
endif
ifeq (,$(wildcard package/lib/lib/nortos_cc32xx/package))
    $(shell $(MKDIR) package/lib/lib/nortos_cc32xx/package)
endif
ifeq (,$(wildcard package/lib/lib/nortos_cc32xx/dpl))
    $(shell $(MKDIR) package/lib/lib/nortos_cc32xx/dpl)
endif
ifeq (,$(wildcard package/lib/lib/nortos_cc32xx/startup))
    $(shell $(MKDIR) package/lib/lib/nortos_cc32xx/startup)
endif
endif
clean::
	-$(RMDIR) package


