#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = gnu.targets.arm.M4{1,0,7.2,1
#
ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/gcc/m4/runtime_debug/package/package_ti.utils.runtime.om4g.dep
package/lib/lib/gcc/m4/runtime_debug/package/package_ti.utils.runtime.om4g.dep: ;
endif

package/lib/lib/gcc/m4/runtime_debug/package/package_ti.utils.runtime.om4g: | .interfaces
package/lib/lib/gcc/m4/runtime_debug/package/package_ti.utils.runtime.om4g: package/package_ti.utils.runtime.c lib/gcc/m4/runtime_debug.a.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4g $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -std=c99  -D_DEBUG_=1 -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_debug -Dxdc_bld__vers_1_0_7_2_1 -g  $(XDCINCS) -I/app/ti/simplelink_cc32xx_sdk_4_10_00_07/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include/newlib-nano -I/app/ti/simplelink_cc32xx_sdk_4_10_00_07/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/gcc/m4/runtime_debug/package/package_ti.utils.runtime.om4g: export LD_LIBRARY_PATH=

package/lib/lib/gcc/m4/runtime_debug/package/package_ti.utils.runtime.sm4g: | .interfaces
package/lib/lib/gcc/m4/runtime_debug/package/package_ti.utils.runtime.sm4g: package/package_ti.utils.runtime.c lib/gcc/m4/runtime_debug.a.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4g -S $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -std=c99  -D_DEBUG_=1 -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_debug -Dxdc_bld__vers_1_0_7_2_1 -g  $(XDCINCS) -I/app/ti/simplelink_cc32xx_sdk_4_10_00_07/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include/newlib-nano -I/app/ti/simplelink_cc32xx_sdk_4_10_00_07/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/gcc/m4/runtime_debug/package/package_ti.utils.runtime.sm4g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/gcc/m4/runtime_debug/Log.om4g.dep
package/lib/lib/gcc/m4/runtime_debug/Log.om4g.dep: ;
endif

package/lib/lib/gcc/m4/runtime_debug/Log.om4g: | .interfaces
package/lib/lib/gcc/m4/runtime_debug/Log.om4g: Log.c lib/gcc/m4/runtime_debug.a.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4g $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -std=c99  -D_DEBUG_=1 -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_debug -Dxdc_bld__vers_1_0_7_2_1 -g  $(XDCINCS) -I/app/ti/simplelink_cc32xx_sdk_4_10_00_07/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include/newlib-nano -I/app/ti/simplelink_cc32xx_sdk_4_10_00_07/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/gcc/m4/runtime_debug/Log.om4g: export LD_LIBRARY_PATH=

package/lib/lib/gcc/m4/runtime_debug/Log.sm4g: | .interfaces
package/lib/lib/gcc/m4/runtime_debug/Log.sm4g: Log.c lib/gcc/m4/runtime_debug.a.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4g -S $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -std=c99  -D_DEBUG_=1 -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_debug -Dxdc_bld__vers_1_0_7_2_1 -g  $(XDCINCS) -I/app/ti/simplelink_cc32xx_sdk_4_10_00_07/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include/newlib-nano -I/app/ti/simplelink_cc32xx_sdk_4_10_00_07/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/gcc/m4/runtime_debug/Log.sm4g: export LD_LIBRARY_PATH=

ifeq (,$(MK_NOGENDEPS))
-include package/lib/lib/gcc/m4/runtime_debug/LoggerText.om4g.dep
package/lib/lib/gcc/m4/runtime_debug/LoggerText.om4g.dep: ;
endif

package/lib/lib/gcc/m4/runtime_debug/LoggerText.om4g: | .interfaces
package/lib/lib/gcc/m4/runtime_debug/LoggerText.om4g: LoggerText.c lib/gcc/m4/runtime_debug.a.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4g $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c  -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -std=c99  -D_DEBUG_=1 -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_debug -Dxdc_bld__vers_1_0_7_2_1 -g  $(XDCINCS) -I/app/ti/simplelink_cc32xx_sdk_4_10_00_07/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include/newlib-nano -I/app/ti/simplelink_cc32xx_sdk_4_10_00_07/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/gcc/m4/runtime_debug/LoggerText.om4g: export LD_LIBRARY_PATH=

package/lib/lib/gcc/m4/runtime_debug/LoggerText.sm4g: | .interfaces
package/lib/lib/gcc/m4/runtime_debug/LoggerText.sm4g: LoggerText.c lib/gcc/m4/runtime_debug.a.mak
	@$(RM) $@.dep
	$(RM) $@
	@$(MSG) clm4g -S $< ...
	$(gnu.targets.arm.M4.rootDir)/bin/arm-none-eabi-gcc -c -MD -MF $@.dep -x c -S -Wunused -Wunknown-pragmas -ffunction-sections -fdata-sections  -mcpu=cortex-m4 -mthumb -mfloat-abi=soft -mabi=aapcs -g -Dfar= -D__DYNAMIC_REENT__  -std=c99  -D_DEBUG_=1 -Dxdc_target_name__=M4 -Dxdc_target_types__=gnu/targets/arm/std.h -Dxdc_bld__profile_debug -Dxdc_bld__vers_1_0_7_2_1 -g  $(XDCINCS) -I/app/ti/simplelink_cc32xx_sdk_4_10_00_07/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include/newlib-nano -I/app/ti/simplelink_cc32xx_sdk_4_10_00_07/kernel/tirtos/packages/gnu/targets/arm//libs/install-native/arm-none-eabi/include -o $@ $<
	-@$(FIXDEP) $@.dep $@.dep
	
package/lib/lib/gcc/m4/runtime_debug/LoggerText.sm4g: export LD_LIBRARY_PATH=

clean,m4g ::
	-$(RM) package/lib/lib/gcc/m4/runtime_debug/package/package_ti.utils.runtime.om4g
	-$(RM) package/lib/lib/gcc/m4/runtime_debug/Log.om4g
	-$(RM) package/lib/lib/gcc/m4/runtime_debug/LoggerText.om4g
	-$(RM) package/lib/lib/gcc/m4/runtime_debug/package/package_ti.utils.runtime.sm4g
	-$(RM) package/lib/lib/gcc/m4/runtime_debug/Log.sm4g
	-$(RM) package/lib/lib/gcc/m4/runtime_debug/LoggerText.sm4g

lib/gcc/m4/runtime_debug.a: package/lib/lib/gcc/m4/runtime_debug/package/package_ti.utils.runtime.om4g package/lib/lib/gcc/m4/runtime_debug/Log.om4g package/lib/lib/gcc/m4/runtime_debug/LoggerText.om4g lib/gcc/m4/runtime_debug.a.mak

clean::
	-$(RM) lib/gcc/m4/runtime_debug.a.mak
